#!/bin/bash
 if [[ -z "$PYFILE" ]]; then
 echo "Error: The PYFILE environment is not set."
 exit 1
 fi

 if [[ ! -f "$PYFILE" ]]; then
 echo "Error: The specified Python file does not exist."
 exit 1

 fi

 python3 "$PYFILE"
